## 04. 판다스 - 데이터 핸들링

* 판다스 : 행과 열로 이뤄진 2차원 데이터를 효율적으로 가공/처리할 수 있는 다양하고 훌륭한 기능을 제공
* 넘파이보다 훨씬 유연하고 편리하게 데이터 핸들링을 가능하게 함

### [판다스 시작 - 파일을 DataFrame으로 로딩, 기본 API]

In [181]:
import pandas as pd

In [182]:
from google.colab import files
uploaded = files.upload()

Saving titanic_train_chu.csv to titanic_train_chu (1).csv

* 필드가 구분되어 있다면 : read_csv('파일명', sep/'\t')
* sep 인자를 생략 : 자동으로 콤마로 할당 (sep=',')

In [183]:
titanic_df = pd.read_csv("titanic_train_chu.csv")

In [184]:
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [185]:
print('titanic 변수 type:', type(titanic_df))
titanic_df

titanic 변수 type: <class 'pandas.core.frame.DataFrame'>

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0              1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1              2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2              3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
3              4         1       1  Futrelle, M...  female  35.0      1      0          113803  53.1000  C123        S
4              5         0       3  Allen, Mr. ...    male  35.0      0      0          373450   8.0500   NaN        S
..           ...       ...     ...             ...     ...   ...    ...    ...             ...      ...   ...      ...
886          887         0       2  Montvila, R...    male  27.0      0      0          211536  13.0000   NaN        S
887          888         1       1  Graham, Mis...  female  19.0      0      0          112053  30.0000   B42        S
888          889         0       3  Johnston, M...  female   NaN      1      2      W./C. 6607  23.4500   NaN        S
889          890         1       1  Behr, Mr. K...    male  26.0      0      0          111369  30.0000  C148        C
890          891         0       3  Dooley, Mr....    male  32.0      0      0          370376   7.7500   NaN        Q

[891 rows x 12 columns]

* DataFrame.head() : DataFrame의 맨 앞에 있는 N개의 로우를 반환 (Default : 5개)

In [186]:
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

* DataFrame의 행과 열 크기를 알아보기 : 생성된 DataFrame 객체의 shape 변수를 이용
* shape : DataFrame의 행과 열을 튜플 형태로 반환

In [187]:
print('DataFrame 크기 :', titanic_df.shape)

# 418개의 로우와 11개의 칼럼

DataFrame 크기 : (891, 12)

[info()]
* 총 데이터 건수와 데이터 타입, Null 건수를 알 수 있음

In [188]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

[describe()]
* 칼럼별 숫자형 데이터값의 n-percentile 분포도, 평균값, 최댓값, 최솟값을 나타낸다
* 오직 숫자형(int, float 등) 칼럼의 분포도만 조사하며 자동으로 object 타입의 칼럼은 출력에서 제외
* 숫자 형 칼럼에 대한 개략적인 데이터 분포도를 확인할 수 있음

In [189]:
titanic_df.describe()

       PassengerId    Survived      Pclass         Age       SibSp       Parch        Fare
count   891.000000  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std     257.353842    0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min       1.000000    0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%     446.000000    0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%     668.500000    1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

* count : not Null인 데이터 건수
* mean : 전체 데이터의 평균값
* std : 표준편차
* min : 최솟값
* max : 최댓값
* 25% : 25 percentile 값

[ value_counts() ]
* 해당 칼럼값의 유형과 건수를 확인 할 수 있음, 지정된 칼럼의 데이터값 건수를 반환함
* 데이터 분포도를 확인하는 데 매우 유용한 함수

In [190]:
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)

# 많은 건수 순서로 정렬되어 값을 반환

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [191]:
titanic_pclass = titanic_df['Pclass']
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>

In [192]:
titanic_pclass.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [193]:
value_counts = titanic_df['Pclass'].value_counts()
print(type(value_counts))
print(value_counts)

<class 'pandas.core.series.Series'>
Pclass
3    491
1    216
2    184
Name: count, dtype: int64

* 칼럼 값별 데이터 건수를 반환하므로 고유 칼럼 값을 식별자로 사용할 수 있음
* 모든 인덱스는 고유성이 보장

### [DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환]

#### (1) 넘파이 ndarray, 리스트, 딕셔너리를 DataFrame으로 변환하기

* DataFrame으로 변환 시 칼럼명을 지정
* DataFrame은 기본적으로 행과 열을 가지는 2차원 데이터

* 1차원 형태의 리스트와 넘파이 ndarray를 DataFrame으로 변환

In [194]:
import numpy as np

# 1차원 형태의 데이터를 기반으로 DataFrame을 생성할 때 칼럼명은 한 개만 필요

col_name1 = ['col1']

list1 = [1,2,3]
array1 = np.array(list1)
print('array1 shape:', array1.shape)

# 리스트를 이용해 DataFrame 생성.
df_list1 = pd.DataFrame(list1, columns=col_name1)
print('1차원 리스트로 만든 DataFrame:\n', df_list1)

# 넘파이 ndarray를 이용해 DataFrame 생성.
df_array1 = pd.DataFrame(array1, columns=col_name1)
print('1차원 ndarray로 만든 DataFrame:\n', df_array1)

array1 shape: (3,)
1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3

* 2차원 형태의 데이터를 기반으로 DataFrame을 생성할 때

In [195]:
# 3개의 칼럼명이 필요
col_name2 = ['col1', 'col2', 'col3']

# 2행x3열 형태의 리스트와 ndarray 생성 후 이를 DataFrame으로 변환
list2 = [[1,2,3],
         [11,12,13]]
array2 = np.array(list2)

print('array2 shape:', array2.shape)

df_list2 = pd.DataFrame(list2, columns = col_name2)
print('2차원 리스트로 만든 DataFrame:\n', df_list2)

df_array2 = pd.DataFrame(array2, columns = col_name2)
print('2차원 ndarray로 만든 DataFrame:\n', df_array2)

array2 shape: (2, 3)
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13

* 딕셔너리를 DataFrame으로 변환

In [196]:
# Key는 문자열 칼럼명으로 매핑, Value는 리스트 형(또는 ndarray) 칼럼 데이터로 매핑

dict = {'col1':[1,11],'col2':[2,12],'col3':[3,13]}
df_dict = pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n', df_dict)

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13

#### (2) DataFrame을 넘파이 ndarray, 리스트, 딕셔너리로 변환

In [197]:
# DataFrame을 ndarray로 변환
array3 = df_dict.values
print('df_dict.values 타입:', type(array3), 'df_dict.values shape:', array3.shape)
print(array3)

df_dict.values 타입: <class 'numpy.ndarray'> df_dict.values shape: (2, 3)
[[ 1  2  3]
 [11 12 13]]

In [198]:
# DataFrame을 리스트로 변환
list3 = df_dict.values.tolist()
print('df_dict.values.tolist() 타입 :', type(list3))
print(list3)

df_dict.values.tolist() 타입 : <class 'list'>
[[1, 2, 3], [11, 12, 13]]

In [199]:
# DataFrame을 딕셔너리로 변환
dict3 = df_dict.to_dict('list')
print('\n df_dict.to_dict() 타입 :', type(dict3))
print(dict3)

 df_dict.to_dict() 타입 : <class 'dict'>
{'col1': [1, 11], 'col2': [2, 12], 'col3': [3, 13]}

### [DataFrame의 칼럼 데이터 세트 생성과 수정]

In [200]:
# 새로운 칼럼 Age_0 을 추가, 일괄적으로 0 값을 할당
titanic_df['Age_0']=0
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0

In [201]:
# 기존 칼럼 Series의 데이터를 이용해 새로운 칼럼 Series를 만들기

titanic_df['Age_by_10'] = titanic_df['Age']*10
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch'] + 1
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      220.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      380.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      260.0          1

In [202]:
# 'Age_by_10' 칼럼 값을 일괄적으로 기존 값 + 100으로 업데이트
titanic_df['Age_by_10'] = titanic_df['Age_by_10'] + 100
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      320.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      480.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      360.0          1

### [DataFrame 데이터 삭제]

drop() 매서드
* DataFrame.drop(labels=None, axis=0, index=None, columns=None, level=None, inplace=False, errors='raise')
* axis=0 : 로우 방향, axis=1 : 칼럼 방향
* axis = 0 삭제 : 기존 칼럼 값을 가공하여 새로운 칼럼을 만들고 삭제
* axis = 1 삭제 : 이상치 데이터를 삭제

In [203]:
# 'Age_0' 칼럼 삭제
titanic_drop_df = titanic_df.drop('Age_0', axis=1)
titanic_drop_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      320.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      480.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      360.0          1

In [204]:
# 원본 데이터 확인
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      320.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      480.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      360.0          1

* inplace = False로 설정 : 'Age_0' 칼럼이 여전히 존재 (디폴트 값)
* inplace = True로 설정 : 자신의 DataFrame의 데이터를 삭제
* 여러 개의 칼럼을 삭제 : 리스트 형태로 삭제하고자 하는 칼럼 명을 입력

In [205]:
drop_result = titanic_df.drop(['Age_0', 'Age_by_10', 'Family_No'], axis=1, inplace=True)
print('inplace=True로 drop 후 반환한 값:', drop_result)
titanic_df.head(3)

inplace=True로 drop 후 반환한 값: None

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

* 유의할 점 : drop() 시 inplace=True로 설정하면 반환 값이 None이 됨
* titanic_df = titanic_df.drop(['Age_0', 'Age_by_10', 'Family_No'], axis=1, inplace=True) : titanic_df 객체 변수를 아예 None으로 만듦

In [206]:
# axis = 0으로 설정해 index0,1,2 로우를 삭제

pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 15)
print('###before axis drop ###')
print(titanic_df.head(3))

titanic_df.drop([0,1,2], axis=0, inplace=True)

print('### after axis 0 drop ####')
print(titanic_df.head(3))

###before axis drop ###
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
### after axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q

* axis : DataFrame의 로우를 삭제할 때는 axis=0, 칼럼을 삭제할 때는 axis=1
* 원본 DataFrame은 유지하고 드롭된 DataFrame을 새롭게 객체 변수로 받고 싶다면 Inplace=False로 설정 (디폴트 값이 False)
* 원본 DataFrame에 드롭된 결과를 적용할 경우에는 inplace=True를 적용
```
titanic_drop_df = titanic_df.drop('Age=0', axis=1, inplace=False)
```
* 원본 DataFrmae에서 드롭된 DataFrame을 다시 원본 DataFrmae 객체 변수로 할당하면 원본 DataFrame에서 드롭된 결과를 적용할 경우와 같음 (단, 기존 원본 DataFrame 객체 변수는 메모리에서 추후 제거됨.)
```
titanic_df = titanic_df.drop('Age_0', axis=1, inplace=False)
```

### [Index 객체]

In [207]:
# 원본 파일 다시 로딩
titanic_df = pd.read_csv('titanic_train_chu.csv')

# index 객체 추출
indexes = titanic_df.index
print(indexes)

# Index 객체를 실제 값 array로 변환
print('index 객체 array 값:\n', indexes.values)

RangeIndex(start=0, stop=891, step=1)
index 객체 array 값:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647
 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665
 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683
 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701
 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719
 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827
 828 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845
 846 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863
 864 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881
 882 883 884 885 886 887 888 889 890]

* Index 객체 : 식별성 데이터를 1차원 array로 가지고 있음. ndarray와 유사하게 단일 값 반환 및 슬라이싱도 가능

In [208]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6

* 한 번 만들어진 DataFrame 및 Series의 Index 객체는 함부로 변경 불가능

In [209]:
# 첫 번째 Index 객체의 값을 5로 변경하는 작업은 수행할 수 없음

indexes[0] = 5

TypeError: Index does not support mutable operations

* Series 객체는 Index 객체를 포함, Series 객체에 연산 함수를 적용할 때 Index는 연산에서 제외
* Index는 오직 식별용으로만 사용

In [210]:
series_fair = titanic_df['Fare']
print('Fair Series max 값:', series_fair.max())
print('Fair Series sum 값:', series_fair.sum())
print('sum() Fair Series:', sum(series_fair))
print('Fair Series + 3:\n', (series_fair+3).head(3))

Fair Series max 값: 512.3292
Fair Series sum 값: 28693.9493
sum() Fair Series: 28693.949299999967
Fair Series + 3:
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64

[reset_index()]

* DataFrame 및 Series에 reset_index() 매서드를 수행하면 새롭게 인덱스를 연속 숫자 형으로 할당하여 기존 인덱스는 'index'라는 새로운 칼럼 명으로 추가

In [211]:
titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

   index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0      0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1      1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2      2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

* reset_index() : 인덱스가 연속된 int 숫자형 데이터가 아닐 경우에 다시 이를 연속 int 숫자형 데이터로 만들 때 주로 사용

In [212]:
# Series의 'Pclass' 고유 값이 식별자 인덱스 역할을 함
print('### before reset_index ###')
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)
print('value_counts 객체 변수 타입:', type(value_counts))


# 연속형 숫자형 인덱스가 고유 식별자로 더 적합
new_value_counts = value_counts.reset_index(inplace=False)

print('### after reset_index ###')
print(new_value_counts)
print('new_value_counts 객체 변수 타입:', type(new_value_counts))
# Series가 아닌 DataFrame이 반환됨

### before reset_index ###
Pclass
3    491
1    216
2    184
Name: count, dtype: int64
value_counts 객체 변수 타입: <class 'pandas.core.series.Series'>
### after reset_index ###
   Pclass  count
0       3    491
1       1    216
2       2    184
new_value_counts 객체 변수 타입: <class 'pandas.core.frame.DataFrame'>

### [데이터 셀렉션 및 필터링]

#### (1) DataFrame의 [ ] 연산자
* 넘파이와 DataFrmae 간 데이터 셀렉션에서 가장 유의해야 함
* 넘파이에서 [ ] 연산자 : 행의 위치, 열의 위치, 슬라이싱 범위 등을 지정해 데이터를 가져올 수 있음
* DataFrame 바로 뒤 [ ] 연산자 : 칼럼 명 문자(칼럼 명의 리스트 객체), 인덱스로 변환 가능한 표현식
* DataFrame 뒤에 있는 [ ] : 칼럼만 지정할 수 있는 '칼럼 지정 연산자'로 이해하기

* DataFrame['칼럼1의 칼럼명', '칼럼2의 칼럼명']

In [213]:
print('단일 칼럼 데이터 추출:\n', titanic_df['Pclass'].head)(3)
print('\n여러 칼럼의 데이터 추출:\n', titanic_df[['Survived','Pclass']].head(3))
print('[]안에 숫자 index는 KeyError 오류 발생"\n', titanic_df[0])

단일 칼럼 데이터 추출:
 <bound method NDFrame.head of 0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64>

TypeError: 'NoneType' object is not callable

* 판다스의 인덱스 형태로 변환 가능한 표현식은 [ ] 내에 입력 가능

In [214]:
titanic_df[0:2]

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0  A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0   PC 17599  71.2833   C85        C

* 불린 인덱싱 표현도 가능

In [216]:
# Pclass 칼럼 값이 3인 데이터 3개만 추출
titanic_df[titanic_df['Pclass']==3].head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket   Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171  7.250   NaN        S
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...  7.925   NaN        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450  8.050   NaN        S

* DataFrame 뒤의 [ ] 연산자의 입력 인자가 여러 가지 형태이므로 사용할 때 혼동을 줌
* DataFrame 바로 뒤의 [ ] 연산자는 넘파이의 [ ]나 Series의 [ ]와 다르다
* DataFrame 바로 뒤의 [ ] 내 입력 값은 칼럼명을 지정해 칼럼 지정 연산에 사용하거나 불린 인덱스 용도로만 사용
* DataFrame[0:2]와 같은 슬라이싱 연산으로 데이터를 추출한느 방법은 사용하지 않기

#### (2) DataFrame ix[ ] 연산자
* 여러 혼돈의 여지가 있어 사라질 예정

In [217]:
print('칼럼 위치 기반 인덱싱 데이터 추출:', titanic_df.ix[0,2])
print('칼럼 명 기반 인덱싱 데이터 추출:', titanic_df.ix[0,'Pclass'])

AttributeError: 'DataFrame' object has no attribute 'ix'

In [218]:
data = {'Name' : ['Chulmin', 'Eunkyung', 'Jinwoong', 'Soobeom'],
        'Year' : [2011, 2016, 2015, 2015],
        'Gender' : ['Male', 'Female', 'Male', 'Male']
       }
data_df = pd.DataFrame(data, index = ['one', 'two', 'three', 'four'])
data_df

           Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

#### (3) 명칭 기반 인덱싱과 위치 기반 인덱싱의 구분
* 명칭(Label) 기반 인덱싱 : 칼럼의 명칭을 기반으로 위치를 지정하는 방식 (명칭으로 열 위치를 지정)
* 위치(Position) 기반 인덱싱 : 0을 출발점으로 하는 가로축, 세로축 좌표 기반의 행과 열 위치를 기반으로 데이터를 지정 (행, 열 값으로 정수가 입력)

In [220]:
# data_df를 reset_index()로 새로운 숫자형 인덱스를 생성
data_df_reset = data_df.reset_index()
data_df_reset = data_df_reset.rename(columns={'index':'old_index'})

# 인덱스 값에 1을 더해서 1부터 시작하는 새로운 인덱스값 생성
data_df_reset.index = data_df_reset.index+1
data_df_reset

  old_index      Name  Year  Gender
1       one   Chulmin  2011    Male
2       two  Eunkyung  2016  Female
3     three  Jinwoong  2015    Male
4      four   Soobeom  2015    Male

In [221]:
data_df_reset.ix[1,1]

AttributeError: 'DataFrame' object has no attribute 'ix'

#### (4) DataFrame iloc[ ] 연산자
* iloc[ ] : 위치 기반 인덱싱만 허용, 행과 열 값으로 integer 또는 integer 형의 슬라이싱, 팬시 리스트 값을 입력

In [222]:
data_df.iloc[0,0]

'Chulmin'

In [223]:
# 위치 인덱싱이 아닌 명칭을 입력하면 오류 발생
data_df.iloc[0,'Name']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [224]:
# 문자열 인덱스를 행 위치에 입력해도 오류 발생
data_df.iloc['one',0]

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [225]:
# data_df를 reset_index()로 1부터 시작하는 새로운 정수형 인덱스값으로 변경한 data_df_reset에 iloc[0,1]을 적용
data_df_reset.iloc[0,1]

'Chulmin'

#### (5) DataFrame loc[ ] 연산자
* loc[ ] : 명칭 기반으로 데이터를 추출
* 행 위치 : DataFrame index 값을, 열 위치 : 칼럼 명

In [226]:
data_df.loc['one','Name']

'Chulmin'

* index가 숫자 형일 수 있음 : 무조건 문자열을 입력한다는 선입견은 안됨

In [227]:
# data_df를 reset_index()로 1부터 시작하는 새로운 정수형 인덱스값으로 변경한 data_df_reset에 loc[0,1]을 적용
data_df_reset.loc[1,'Name']

'Chulmin'

In [228]:
# index 값이 0인 행이 없으므로 오류 발생
data_df_reset.loc[0,'Name']

KeyError: 0

loc[ ] 에 슬라이싱 기호 ':'를 적용할 때 유의할 점
* 일반적인 슬라이싱 : '시작 값' : '종료 값' == 시작 값 ~ 종료 값-1
* loc[ ]에 슬라이싱 기호 : '시작 값' : '종료 값' == 시작 값 ~ 종료 값

In [230]:
# print('명칭 기반 ix slicing\n', data_df.ix['one': 'two', 'Name'], '\n')
print('위치 기반 iloc slicing\n', data_df.iloc[0:1,0], '\n')
print('명칭 기반 loc slicing\n', data_df.loc['one': 'two', 'Name'], '\n')

위치 기반 iloc slicing
 one    Chulmin
Name: Name, dtype: object

명칭 기반 loc slicing
 one     Chulmin
two    Eunkyung
Name: Name, dtype: object

* 인덱스가 정수형이면 명칭 기반 loc[ ] 이용시 조심

In [231]:
# 인덱스 명칭이 1,2인 2개의 데이터를 반환
print(data_df_reset.loc[1:2,'Name'])

1     Chulmin
2    Eunkyung
Name: Name, dtype: object

* 위치 기반 ix[ ]

In [232]:
# 1:2는 1개의 데이터를 반환
# print(data_df.ix[1:2,'Name'])

AttributeError: 'DataFrame' object has no attribute 'ix'

ix, iloc, loc의 문제점과 주의할 점
* 명칭 기반 인덱싱과 위치 기반 인덱싱의 차이를 이해하기
- 명칭 기반 인덱싱 : DataFrame의 인덱스나 칼럼명으로 데이터에 접근
- 위치 기반 인덱싱 : 0부터 시작하는 행, 열의 위치 좌표에만 의존
* iloc[ ]는 위치 기반 인덱싱만 가능, 행과 열 위치 값으로 정수형 값을 지정해 원하는 데이터를 반환
* loc [ ]는 명칭 기반 인덱싱만 가능, 행 위치에 DataFrame 인덱스가 오며 열 위치에는 칼럼 명을 지정해 원하는 데이터를 반환
* 명칭 기반 인덱싱에서 슬라이싱을 '시작점:종료점'으로 지정 : 시작점과 종료점을 포함한 위치에 있는 데이터를 반환

#### (6) 불린 인덱싱

In [234]:
# 새롭게 타이타닉 데이터 세트를 로드, 승객 중 나이가 60세 이상인 데이터를 추출
titanic_df = pd.read_csv("titanic_train_chu.csv")
titanic_boolean = titanic_df[titanic_df['Age']>60]
print(type(titanic_boolean))
titanic_boolean

<class 'pandas.core.frame.DataFrame'>

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked
33            34         0       2  Wheadon, Mr...    male  66.0      0      0   C.A. 24579   10.5000          NaN        S
54            55         0       1  Ostby, Mr. ...    male  65.0      0      1       113509   61.9792          B30        C
96            97         0       1  Goldschmidt...    male  71.0      0      0     PC 17754   34.6542           A5        C
116          117         0       3  Connors, Mr...    male  70.5      0      0       370369    7.7500          NaN        Q
170          171         0       1  Van der hoe...    male  61.0      0      0       111240   33.5000          B19        S
252          253         0       1  Stead, Mr. ...    male  62.0      0      0       113514   26.5500          C87        S
275          276         1       1  Andrews, Mi...  female  63.0      1      0        13502   77.9583           D7        S
280          281         0       3  Duane, Mr. ...    male  65.0      0      0       336439    7.7500          NaN        Q
326          327         0       3  Nysveen, Mr...    male  61.0      0      0       345364    6.2375          NaN        S
438          439         0       1  Fortune, Mr...    male  64.0      1      4        19950  263.0000  C23 C25 C27        S
456          457         0       1  Millet, Mr....    male  65.0      0      0        13509   26.5500          E38        S
483          484         1       3  Turkula, Mr...  female  63.0      0      0         4134    9.5875          NaN        S
493          494         0       1  Artagaveyti...    male  71.0      0      0     PC 17609   49.5042          NaN        C
545          546         0       1  Nicholson, ...    male  64.0      0      0          693   26.0000          NaN        S
555          556         0       1  Wright, Mr....    male  62.0      0      0       113807   26.5500          NaN        S
570          571         1       2  Harris, Mr....    male  62.0      0      0  S.W./PP 752   10.5000          NaN        S
625          626         0       1  Sutton, Mr....    male  61.0      0      0        36963   32.3208          D50        S
630          631         1       1  Barkworth, ...    male  80.0      0      0        27042   30.0000          A23        S
672          673         0       2  Mitchell, M...    male  70.0      0      0   C.A. 24580   10.5000          NaN        S
745          746         0       1  Crosby, Cap...    male  70.0      1      1    WE/P 5735   71.0000          B22        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0       113572   80.0000          B28      NaN
851          852         0       3  Svensson, M...    male  74.0      0      0       347060    7.7750          NaN        S

In [237]:
# 원하는 칼럼 명만 별도로 추출
# 60세 이상 승객의 나이와 이름만 추출
titanic_df[titanic_df['Age'] >= 60][['Name', 'Age']].head()

               Name   Age
33   Wheadon, Mr...  66.0
54   Ostby, Mr. ...  65.0
96   Goldschmidt...  71.0
116  Connors, Mr...  70.5
170  Van der hoe...  61.0

In [238]:
titanic_df.loc[titanic_df['Age'] >= 60][['Name', 'Age']].head()

               Name   Age
33   Wheadon, Mr...  66.0
54   Ostby, Mr. ...  65.0
96   Goldschmidt...  71.0
116  Connors, Mr...  70.5
170  Van der hoe...  61.0

* and 조건일 때는 &
* or 조건일 때는 |
* Not 조건일 때는 ~

In [239]:
titanic_df[ (titanic_df['Age']>60) & (titanic_df['Pclass']==1) & (titanic_df['Sex']=='female') ]

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

In [240]:
# 개별 조건을 변수에 할당하고 이들 변수를 결합해서 불린 인덱싱을 수행
cond1 = titanic_df['Age']>60
cond2 = titanic_df['Pclass']==1
cond3 = titanic_df['Sex']=='female'
titanic_df[cond1&cond2&cond3]

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

### [정렬, Aggregation 함수, GroupBy 적용]

#### (1) DataFrame, Series의 정렬 - sort_values()
[ sort_values() ]
* by 로 특정 칼럼을 입력 : 해당 칼럼으로 정렬을 수행
* ascending = True : 오름차순 (디폴트)
* ascending = False : 내림차순
* inplace = False 로 설정 : sort_values()를 호출한 DataFrame은 그대로 유지하며 정렬된 DataFrame을 결과로 반환 (디폴트)
* inplace = True 로 설정 : 호출한 DataFrame은 그대로 적용

In [241]:
# Name 칼럼으로 오름차순 정렬해 반환
titanic_sorted = titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket   Fare Cabin Embarked
845          846         0       3  Abbing, Mr....    male  42.0      0      0  C.A. 5547   7.55   NaN        S
746          747         0       3  Abbott, Mr....    male  16.0      1      1  C.A. 2673  20.25   NaN        S
279          280         1       3  Abbott, Mrs...  female  35.0      1      1  C.A. 2673  20.25   NaN        S

In [242]:
# 여러 개의 칼럼으로 정렬하려면 by에 리스트 형식으로
# Pclass와 Name를 내림차순으로 정렬한 경과를 반환
titanic_sorted = titanic_df.sort_values(by=['Pclass', 'Name'], ascending=False)
titanic_sorted.head(3)

     PassengerId  Survived  Pclass            Name   Sex   Age  SibSp  Parch    Ticket  Fare Cabin Embarked
868          869         0       3  van Melkebe...  male   NaN      0      0    345777   9.5   NaN        S
153          154         0       3  van Billiar...  male  40.5      0      2  A/5. 851  14.5   NaN        S
282          283         0       3  de Pelsmaek...  male  16.0      0      0    345778   9.5   NaN        S

####(2) Aggregation 함수 적용
* 모든 칼럼에 해당 aggregation을 적용함

In [243]:
# 모든 칼럼에 count() 결과를 반환
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [244]:
# 특정 칼럼에 적용 : 대상 칼럼들만 추출하여 적용
titanic_df[['Age','Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

#### (3) groupby() 적용
* DataFrame의 groupby() 사용 시 입력 파라미터 by에 칼럼을 입력하면 대상 칼럼으로 groupby 됨.
* DataFrame에 groupby()를 호출하면 DataFrameGroupBy라는 또 다른 형태의 DataFrame을 반환

In [245]:
# groupby(by='Pclass')를 호출 : Pclass 칼럼 기준으로 GroupBy 된 DataFrameGroupBy 객체를 반환
titanic_groupby = titanic_df.groupby(by = 'Pclass')
print(type(titanic_groupby))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

In [ ]:
# groupby() 대상 칼럼을 제외한 모든 칼럼에 해당 aggregation 함수를 적용
titanic_groupby = titanic_df.groupby('Pclass').count()
titanic_groupby

* DataFrame의 groupby()에 특정 칼럼만 aggregation 함수를 적용 : groupby()로 반환된 DataFrameGroupBy 객체에 해당 칼럼을 필터링한 뒤 aggregation 함수를 적용

In [247]:
# PassengerId와 Survived 칼럼에만 count()를 수행
titanic_groupby = titanic_df.groupby('Pclass')[['PassengerId', 'Survived']].count()
titanic_groupby

        PassengerId  Survived
Pclass
1               216       216
2               184       184
3               491       491

* agg() : 서로 다른 aggregation 함술르 적용

In [248]:
titanic_df.groupby('Pclass')['Age'].agg([max,min])

<ipython-input-248-788e48698d74>:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max,min])
<ipython-input-248-788e48698d74>:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max,min])

         max   min
Pclass
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [249]:
agg_format = {'Age':'max', 'SibSp':'sum', 'Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

         Age  SibSp       Fare
Pclass
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

### [결손 데이터 처리하기]
* Null을 NaN으로 표시
* 머신러닝 알고리즘은 이 NaN 값을 처리하지 않으므로 이 값을 다른 값으로 대체
* NaN 값은 평균, 총합 등의 함수 연산 시 제외됨

#### (1) isna()로 결손 데이터 여부 확인
[isna()]
* 데이터가 NaN 인지 아닌지 알려줌

In [251]:
titanic_df.isna().head(3)

   PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket   Fare  Cabin  Embarked
0        False     False   False  False  False  False  False  False   False  False   True     False
1        False     False   False  False  False  False  False  False   False  False  False     False
2        False     False   False  False  False  False  False  False   False  False   True     False

In [252]:
# sum() 함수 이용하여 결손 데이터의 개수 구하기
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

#### (2) fillna()로 결손 데이터 대체하기

In [253]:
# 'Cabin' 칼럼의 NaN 값을 'C000'으로 대체
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500  C000        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250  C000        S

* fillna()를 이용해 반환 값을 다시 받거나 inplace=True 파라미터를 fillna()에 추가해야 실제 데이터 세트 값이 변경됨

In [254]:
# 'Age' 칼럼의 NaN 값을 평균 나이로, 'Embarked' 칼럼의 NaN 값을 'S'로 대체해 모든 결손 데이터를 처리
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

### [apply lambda 식으로 데이터 가공]
* apply lambda : 복잡한 데이터 가공이 필요한 경우 이용

* lambda 식 : 파이썬에서 함수형 프로그래밍을 지원하기 위해 만들어짐

In [255]:
def get_square(a):  # 함수명과 입력 인자를 먼저 선언
    return a**2     # 함수 내에서 입력 인자를 가공한 뒤 결괏값을 return과 같은 문법으로 반환

print('3의 제곱은:', get_square(3))

3의 제곱은: 9

In [258]:
# lambda 사용
lambda_square = lambda x : x**2   # ':'로 입력 인자와 반환될 입력 인자의 계산식을 분리 (입력인자 : 계산식)
print('3의 제곱은:', lambda_square(3))

3의 제곱은: 9

In [261]:
# map() 함수 결합 : 여러 개의 값을 입력 인자로 사용해야 할 경우
a = [1,2,3]
squares = map(lambda x : x**2,a)
list(squares)

[1, 4, 9]

apply에 lambda 식을 적용해 데이터 가공

In [262]:
# 'Name' 칼럼의 문자열 개수를 별도의 칼럼인 'Name_len'에서 생성
titanic_df['Name_len'] = titanic_df['Name'].apply(lambda x : len(x))
titanic_df[['Name', 'Name_len']].head(3)

             Name  Name_len
0  Braund, Mr....        23
1  Cumings, Mr...        51
2  Heikkinen, ...        22

* if else 절 이용

In [263]:
# 나이가 15세 미만이면 child, 그렇지 않으면 adult로 구분
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x : 'Child' if x <= 15 else 'Adult')
titanic_df[['Age','Child_Adult']].head(8)

         Age Child_Adult
0  22.000000       Adult
1  38.000000       Adult
2  26.000000       Adult
3  35.000000       Adult
4  35.000000       Adult
5  29.699118       Adult
6  54.000000       Adult
7   2.000000       Child

* if else 이용할 때, if 절의 경우 if 식보다 반환 값을 먼저 기술해야 함
* else if 는 지원하지 않음

In [264]:
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : 'Child' if x<= 15 else ('Adult' if x <= 60 else 'Elderly'))
titanic_df['Age_cat'].value_counts()

Age_cat
Adult      786
Child       83
Elderly     22
Name: count, dtype: int64

In [ ]:
# 나이에 따라 세분화된 분류를 수행하는 함수 생성
def get_category(age):
    cat = ''
    if age <= 5: cat = 'Baby'
    elif age <= 12: cat = 'Child'
    elif age <= 18: cat = 'Teenager'
    elif age <= 25: cat = 'Student'
    elif age <= 35: cat = 'Young Adult'
    elif age <= 60: cat = 'Adult'
    else : cat = 'Elderly'

    return cat

# lambda 식에 위에서 생성한 get_category() 함수를 반환값으로 지정
# get_category(X)는 입력값으로 'Age' 칼럼 값을 받아서 해당하는 cat 반환
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : get_category(x))
titanic_df[['Age', 'Age_cat']].head()